### ISSUE TITLE
Is it possible to build ffmpeg with SSL support on Windows Subsystem for Linux (WSL)

### ISSUE THREAD

**Issue by asElhadidy** [Microsoft/FFmpegInterop#138]
Is it possible to build ffmpeg with SSL support  (--enable-openssl) on WSL?

I have tried to install openssl using these commands
>sudo apt-get install openssl
>sudo apt-get install libssl-dev

Modified configure to include --enable-openssl option, but it always gives the error "Error: openssl not found"

Is it possible or I need to build openssl on windows system?

**Comment by khouzam** [comment]
Hi @asElhadidy,

Funny you should ask. I just did this last night. I'm gathering the steps and will be posting documentation about how to do this.

Unfortunately, getting the Linux openssl implementation doesn't work, you need a windows version of openssl. You can start with our fork for UWP at https://github.com/microsoft/openssl to get the openssl binaries.

I'll gather up the proper patches and push them on a branch shortly.

**Comment by asElhadidy** [comment]
Hi khouzam,

Great, this will be a very good addition to your excellent work on WSL. 
I'll try to compile openssl on windows as your suggestion. Hopefully, I can get it to work. If not will definitely wait for your patches :)

I'm not an expert on Linux systems but I thought it is possible to cross compile the full ffmpeg stack (and its external libraries) on Linux, is this technically possible or I have misunderstood something?

**Comment by ryanwinter** [comment]
Does he current build of ffmpeg interop include ssl support?

**Comment by asElhadidy** [comment]
Hi ryanwinter ,

No it doesn't include ssl support. Hopefully it will be added shortly.

**Comment by khouzam** [comment]
I've added a preliminary support for building FFmpeg with OpenSSL through [vcpkg](https://github.com/microsoft/vcpkg) a new Microsoft C++ package manager. This is still experimental, but seems to work really well. Please see my last post for issue #136 which talks about it.

If you checkout branch `ffmpeg-openssl` instead of `ffmpeg-uwp`, then openssl support will be included in the build of FFmpeg and you'll be able to playback streams over https.

Please try it out and provide feedback.

**Comment by bvenhaus** [comment]
Hey @khouzam  ,

What you wrote in #136 for vcpkg works well for me with ffmpeg-uwp but when doing the build for ffmpeg-openssl I get an error:

> fatal error C1107: could not find assembly 'windows.foundation.foundationcontract.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable

This was on a machine with VS 2015 & Windows 10 SDK 10.0.14393.0.  

Any chance you know why it's unable to find the file?

Here's my log files:
[make-openssl-x86-uwp-err.log.txt](https://github.com/Microsoft/FFmpegInterop/files/1110543/make-openssl-x86-uwp-err.log.txt)
[make-openssl-x86-uwp-out.log.txt](https://github.com/Microsoft/FFmpegInterop/files/1110544/make-openssl-x86-uwp-out.log.txt)

Thanks,
Bill

**Comment by khouzam** [comment]
Hi @bvenhaus .

Can you show the contents of the C:\Program Files (x86)\Windows Kits\10\References\Windows.Foundation.UniversalApiContract folder?

We might have missed a reference version.

**Comment by bvenhaus** [comment]
Sure. 

![image](https://user-images.githubusercontent.com/6692379/27666065-db0f045e-5c36-11e7-8a72-d6e66d22fbce.png)

**Comment by bvenhaus** [comment]
Hi @khouzam ,

Is there any chance you can upload or send me the compiled packages from your "ffmpeg-openssl" branch?  Today, I installed a fresh copy of Windows 10 with VS 2015 & I'm still seeing the same issue.  I am however able to build OpenSSL independently.  I'd really like to integrate this into my [Home Remote](https://www.microsoft.com/en-us/store/p/home-remote/9nblggh30wp5?rtc=1) app. 

Thanks,
Bill

**Comment by ras0219-msft** [comment]
@bvenhaus I've pushed a branch (`ffmpeg-openssl-contract-fix`) to the main vcpkg repo that _should_ fix this issue. If it does, @khouzam can pull it back into his branch.

Would you mind trying this out?

```
git checkout -b ffmpeg-openssl-contract-fix ffmpeg-openssl
git pull https://github.com/Microsoft/vcpkg ffmpeg-openssl-contract-fix
```

**Comment by khouzam** [comment]
Thanks @ras0219-msft,
I've updated the ffmpeg-openssl branch.

@bvenhaus, can you try it now? I'll build a nuget package but that this will not be an official Microsoft endorsed one.

**Comment by bvenhaus** [comment]
Thanks guys, still getting the same error though.  

@ras0219-msft here's the logs from your branch.

[make-openssl-x86-uwp-err.log.txt](https://github.com/Microsoft/FFmpegInterop/files/1116288/make-openssl-x86-uwp-err.log.txt)
[make-openssl-x86-uwp-out.log.txt](https://github.com/Microsoft/FFmpegInterop/files/1116289/make-openssl-x86-uwp-out.log.txt)

@khouzam here's the logs from your updated branch

[make-openssl-x86-uwp-err.log.txt](https://github.com/Microsoft/FFmpegInterop/files/1116293/make-openssl-x86-uwp-err.log.txt)
[make-openssl-x86-uwp-out.log.txt](https://github.com/Microsoft/FFmpegInterop/files/1116294/make-openssl-x86-uwp-out.log.txt)

Thanks @khouzam That'd be great!  I don't mind if it's not an official Microsoft package.

**Comment by khouzam** [comment]
Ok, here's my personal nuget package link: [FFmpeg-OpenSSL nuget](https://1drv.ms/u/s!AstNugTtUhOYgY-mBRPF1nPJXyZPS80).

**Comment by bvenhaus** [comment]
Thanks!

**Comment by HppZ** [comment]
> Hi @asElhadidy,
> 
> Funny you should ask. I just did this last night. I'm gathering the steps and will be posting documentation about how to do this.
> 
> Unfortunately, getting the Linux openssl implementation doesn't work, you need a windows version of openssl. You can start with our fork for UWP at https://github.com/microsoft/openssl to get the openssl binaries.
> 
> I'll gather up the proper patches and push them on a branch shortly.

PLEASE, I need your documentation about how to build ffmpeg with openssl support.
